### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by jg2002-j** [EngineHub/WorldEditCUI#82]
### The Problem

Hi, it's really hard to see the content inside the selection for at least the cuboid region. Is there anyway to adjust transparency?

### A Solution

Add transparency slider

**Comment by PetyXbron** [comment]
Oh, I need this so bad!!!

**Comment by zml2008** [comment]
The alpha value on selections can be controlled as part of the colour -- it's admittedly a bit finnicky now, a color picker is planned.

**Comment by PetyXbron** [comment]
Hey, this could be your possible solution.
I use `#00000000` instead of `#CC4C4CCC` (default) in the Cuboid Grid Color setting specifically.
![wecui-transparent](https://user-images.githubusercontent.com/35902119/229601202-d381a2fa-a0a8-4d70-939a-240f60f28ca5.png)
In my opinion, this is a more good-looking option.
Yes [jg2002-j](https://github.com/jg2002-j), you maybe need a transparency slider to adjust the rate but for those that did not know, you can use the `#00000000` color code for "disabling" the color.
